# Generated by Django 2.1 on 2018-08-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('sequence', models.IntegerField()),
                ('columnId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.GalleryColumn')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
