# Generated by Django 2.1 on 2018-08-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20180827_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['sequence']},
        ),
    ]
