# Generated by Django 2.1 on 2018-09-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='query',
            field=models.CharField(max_length=1000),
        ),
    ]
