# Generated by Django 2.1 on 2018-09-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_auto_20180905_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='emailId',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
