# Generated by Django 2.1 on 2018-09-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20180905_0509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Done'),
            preserve_default=False,
        ),
    ]
