# Generated by Django 2.1 on 2018-09-08 17:24

import contactus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0005_auto_20180908_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='contactNo',
            field=models.CharField(max_length=20, validators=[contactus.models.ContactUs.validateContactNo]),
        ),
    ]
