# Generated by Django 2.1 on 2018-09-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0006_auto_20180908_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoContactUs', models.ImageField(upload_to='my_details')),
                ('mobileNos', models.CharField(max_length=30)),
                ('emailId', models.EmailField(max_length=254)),
            ],
        ),
    ]
