# Generated by Django 2.1 on 2018-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageslider',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
