# Generated by Django 2.1 on 2018-08-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weoffer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images')),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='thumbnail',
            field=models.ImageField(upload_to='event_thumbnails'),
        ),
    ]
