# Generated by Django 2.1 on 2018-08-09 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weoffer', '0002_auto_20180809_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimages',
            name='event_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='weoffer.Events'),
            preserve_default=False,
        ),
    ]
