# Generated by Django 2.1 on 2018-08-09 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weoffer', '0003_eventimages_event_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='EventImages',
            new_name='EventImage',
        ),
    ]
